// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "Vmu_Msg.h"
///////////////////// VARIABLES ////////////////////
void ani_Animation(lv_obj_t *TargetObject, int delay);

// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_event_SplashScreen(lv_event_t *e);
lv_obj_t *ui_SplashScreen;
lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t *ui_HomeScreen;
lv_obj_t *ui_SpeedMetterBG;
lv_obj_t *ui_SpeedMetter;
lv_obj_t *ui_BatteryMetter;
lv_obj_t *ui_ImgChargeStatus;
lv_obj_t *ui_ImgBatteryStatus;
lv_obj_t *ui_SldBattery;
lv_obj_t *ui_lbOdoValue;
lv_obj_t *ui_lbOdo;
lv_obj_t *ui_lbOdoKm;
lv_obj_t *ui_lbSpeedValue;
lv_obj_t *ui_lbSpeedUnit;
lv_obj_t *ui_imgWarning;
lv_obj_t *ui_imgXinNhanLeft;
lv_obj_t *ui_imgCosPha;
lv_obj_t *ui_imgGear;
lv_obj_t *ui_imgTemOver;
lv_obj_t *ui_imgXinNhanRight;
lv_obj_t *ui_lbBatteryPercent;
lv_obj_t *ui_lbSpeed20;
lv_obj_t *ui_lbSpeed40;
lv_obj_t *ui_lbSpeed60;
lv_obj_t *ui_lbSpeed80;
lv_obj_t *ui_lbSpeed100;
lv_obj_t *ui_lbSpeed120;
lv_obj_t *ui_lbSpeed140;
lv_obj_t *ui_lbSpeed160;
lv_obj_t *ui_lbSpeed0;
lv_obj_t *ui_pnTime;
lv_obj_t *ui_lbTime;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_lbTrip;
lv_obj_t *ui_lbTripKm;
lv_obj_t *ui_lbTripValue;
lv_obj_t *ui_pnDot10;
lv_obj_t *ui_pnDot30;
lv_obj_t *ui_pnDot50;
lv_obj_t *ui_pnDot70;
lv_obj_t *ui_pnDot90;
lv_obj_t *ui_pnDot110;
lv_obj_t *ui_pnDot130;
lv_obj_t *ui_pnDot1;
// CUSTOM VARIABLES

// SCREEN: ui_ChargingScreen
void ui_ChargingScreen_screen_init(void);
lv_obj_t *ui_ChargingScreen;
lv_obj_t *ui_CharingScreenBatteryMetter1;
lv_obj_t *ui_CharingScreenImgChargeStatus1;
lv_obj_t *ui_CharingScreenImgBatteryStatus1;
lv_obj_t *ui_SldBattery1;
lv_obj_t *ui_CharingScreenlbBatteryPercent1;
lv_obj_t *ui_CharingScreenPnTime1;
lv_obj_t *ui_CharingScreenlbTime1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ani_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init( &PropertyAnimation_0);
    lv_anim_set_time( &PropertyAnimation_0, 1000);
    lv_anim_set_user_data( &PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb( &PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values( &PropertyAnimation_0, 0, 50);
    lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay( &PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time( &PropertyAnimation_0, 0);
    lv_anim_set_playback_delay( &PropertyAnimation_0, 0);
    lv_anim_set_repeat_count( &PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay( &PropertyAnimation_0, 0);
    lv_anim_set_early_apply( &PropertyAnimation_0, false);
    lv_anim_set_get_value_cb( &PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start( &PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_SplashScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        ani_Animation(ui_Image1, 0);
    }
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 1500, &ui_HomeScreen_screen_init);
        Bike_SysData.Display.ScreenNow = VMUD_SCREEN_HOME;
        Bike_SysData.Display.TripScreenNow = VMUD_TRIP_SCREEN_TRIP_1;
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
    false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_HomeScreen_screen_init();
    ui_ChargingScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
