// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void ani_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_event_SplashScreen(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_SpeedMetterBG;
extern lv_obj_t * ui_SpeedMetter;
extern lv_obj_t * ui_BatteryMetter;
extern lv_obj_t * ui_ImgChargeStatus;
extern lv_obj_t * ui_ImgBatteryStatus;
extern lv_obj_t * ui_SldBattery;
extern lv_obj_t * ui_lbOdoValue;
extern lv_obj_t * ui_lbOdo;
extern lv_obj_t * ui_lbOdoKm;
extern lv_obj_t * ui_lbSpeedValue;
extern lv_obj_t * ui_lbSpeedUnit;
extern lv_obj_t * ui_imgWarning;
extern lv_obj_t * ui_imgXinNhanLeft;
extern lv_obj_t * ui_imgCosPha;
extern lv_obj_t * ui_imgGear;
extern lv_obj_t * ui_imgTemOver;
extern lv_obj_t * ui_imgXinNhanRight;
extern lv_obj_t * ui_lbBatteryPercent;
extern lv_obj_t * ui_lbSpeed20;
extern lv_obj_t * ui_lbSpeed40;
extern lv_obj_t * ui_lbSpeed60;
extern lv_obj_t * ui_lbSpeed80;
extern lv_obj_t * ui_lbSpeed100;
extern lv_obj_t * ui_lbSpeed120;
extern lv_obj_t * ui_lbSpeed140;
extern lv_obj_t * ui_lbSpeed160;
extern lv_obj_t * ui_lbSpeed0;
extern lv_obj_t * ui_pnTime;
extern lv_obj_t * ui_lbTime;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lbTrip;
extern lv_obj_t * ui_lbTripKm;
extern lv_obj_t * ui_lbTripValue;
extern lv_obj_t * ui_pnDot10;
extern lv_obj_t * ui_pnDot30;
extern lv_obj_t * ui_pnDot50;
extern lv_obj_t * ui_pnDot70;
extern lv_obj_t * ui_pnDot90;
extern lv_obj_t * ui_pnDot110;
extern lv_obj_t * ui_pnDot130;
extern lv_obj_t * ui_pnDot1;
// CUSTOM VARIABLES

// SCREEN: ui_ChargingScreen
void ui_ChargingScreen_screen_init(void);
extern lv_obj_t * ui_ChargingScreen;
extern lv_obj_t * ui_CharingScreenBatteryMetter1;
extern lv_obj_t * ui_CharingScreenImgChargeStatus1;
extern lv_obj_t * ui_CharingScreenImgBatteryStatus1;
extern lv_obj_t * ui_SldBattery1;
extern lv_obj_t * ui_CharingScreenlbBatteryPercent1;
extern lv_obj_t * ui_CharingScreenPnTime1;
extern lv_obj_t * ui_CharingScreenlbTime1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_white_png);    // assets/logo_white.png
LV_IMG_DECLARE(ui_img_charge_off_png);    // assets/Charge_Off.png
LV_IMG_DECLARE(ui_img_charge_on_png);    // assets/Charge_On.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_warning_off_png);    // assets/Warning_Off.png
LV_IMG_DECLARE(ui_img_warning_on_png);    // assets/Warning_On.png
LV_IMG_DECLARE(ui_img_left_off_png);    // assets/Left_Off.png
LV_IMG_DECLARE(ui_img_left_on_png);    // assets/Left_On.png
LV_IMG_DECLARE(ui_img_cos_off_png);    // assets/Cos_Off.png
LV_IMG_DECLARE(ui_img_cos_on_png);    // assets/Cos_On.png
LV_IMG_DECLARE(ui_img_pha_on_png);    // assets/Pha_On.png
LV_IMG_DECLARE(ui_img_n_png);    // assets/N.png
LV_IMG_DECLARE(ui_img_d_png);    // assets/D.png
LV_IMG_DECLARE(ui_img_over_tem_off_png);    // assets/Over_Tem_Off.png
LV_IMG_DECLARE(ui_img_over_tem_on_png);    // assets/Over_Tem_On.png
LV_IMG_DECLARE(ui_img_right_off_png);    // assets/Right_Off.png
LV_IMG_DECLARE(ui_img_right_on_png);    // assets/Right_On.png

// FONTS
LV_FONT_DECLARE(ui_font_Tektur10);
LV_FONT_DECLARE(ui_font_Tektur11);
LV_FONT_DECLARE(ui_font_Tektur128);
LV_FONT_DECLARE(ui_font_Tektur15);
LV_FONT_DECLARE(ui_font_Tektur16);
LV_FONT_DECLARE(ui_font_Tektur24);
LV_FONT_DECLARE(ui_font_Tektur32);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
