// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_SpeedMetterBG;
extern lv_obj_t * ui_SpeedMetter;
extern lv_obj_t * ui_BatteryMetter;
extern lv_obj_t * ui_ImgChargeStatus;
extern lv_obj_t * ui_ImgBatteryStatus;
extern lv_obj_t * ui_SldBattery;
extern lv_obj_t * ui_lbOdoValue;
extern lv_obj_t * ui_lbOdo;
extern lv_obj_t * ui_lbOdoKm;
extern lv_obj_t * ui_lbSpeedValue;
extern lv_obj_t * ui_lbSpeedUnit;
extern lv_obj_t * ui_imgWarning;
extern lv_obj_t * ui_imgXinNhanLeft;
extern lv_obj_t * ui_imgCosPha;
extern lv_obj_t * ui_imgGear;
extern lv_obj_t * ui_imgTemOver;
extern lv_obj_t * ui_imgXinNhanRight;
extern lv_obj_t * ui_lbBatteryPercent;
extern lv_obj_t * ui_lbSpeed20;
extern lv_obj_t * ui_lbSpeed40;
extern lv_obj_t * ui_lbSpeed60;
extern lv_obj_t * ui_lbSpeed80;
extern lv_obj_t * ui_lbSpeed100;
extern lv_obj_t * ui_lbSpeed120;
extern lv_obj_t * ui_lbSpeed140;
extern lv_obj_t * ui_lbSpeed160;
extern lv_obj_t * ui_lbSpeed0;
extern lv_obj_t * ui_pnTime;
extern lv_obj_t * ui_lbTime;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lbTrip;
extern lv_obj_t * ui_lbTripKm;
extern lv_obj_t * ui_lbTripValue;
extern lv_obj_t * ui_pnDot10;
extern lv_obj_t * ui_pnDot30;
extern lv_obj_t * ui_pnDot50;
extern lv_obj_t * ui_pnDot70;
extern lv_obj_t * ui_pnDot90;
extern lv_obj_t * ui_pnDot110;
extern lv_obj_t * ui_pnDot130;
extern lv_obj_t * ui_pnDot1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

