// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SplashScreen.h"
#include "screens/ui_HomeScreen.h"
#include "screens/ui_ChargingScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * ani_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_white_png);    // assets/logo_white.png
LV_IMG_DECLARE(ui_img_charge_off_png);    // assets/Charge_Off.png
LV_IMG_DECLARE(ui_img_charge_on_png);    // assets/Charge_On.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_warning_off_png);    // assets/Warning_Off.png
LV_IMG_DECLARE(ui_img_warning_on_png);    // assets/Warning_On.png
LV_IMG_DECLARE(ui_img_left_off_png);    // assets/Left_Off.png
LV_IMG_DECLARE(ui_img_left_on_png);    // assets/Left_On.png
LV_IMG_DECLARE(ui_img_cos_off_png);    // assets/Cos_Off.png
LV_IMG_DECLARE(ui_img_cos_on_png);    // assets/Cos_On.png
LV_IMG_DECLARE(ui_img_pha_on_png);    // assets/Pha_On.png
LV_IMG_DECLARE(ui_img_n_png);    // assets/N.png
LV_IMG_DECLARE(ui_img_d_png);    // assets/D.png
LV_IMG_DECLARE(ui_img_over_tem_off_png);    // assets/Over_Tem_Off.png
LV_IMG_DECLARE(ui_img_over_tem_on_png);    // assets/Over_Tem_On.png
LV_IMG_DECLARE(ui_img_right_off_png);    // assets/Right_Off.png
LV_IMG_DECLARE(ui_img_right_on_png);    // assets/Right_On.png

// FONTS
LV_FONT_DECLARE(ui_font_Tektur10);
LV_FONT_DECLARE(ui_font_Tektur11);
LV_FONT_DECLARE(ui_font_Tektur128);
LV_FONT_DECLARE(ui_font_Tektur15);
LV_FONT_DECLARE(ui_font_Tektur24);
LV_FONT_DECLARE(ui_font_Tektur16Bold);
LV_FONT_DECLARE(ui_font_Tektur18Bold);
LV_FONT_DECLARE(ui_font_Tektur37Bold);
LV_FONT_DECLARE(ui_font_Tektur15Bold);
LV_FONT_DECLARE(ui_font_Tektur17Medium);
LV_FONT_DECLARE(ui_font_Tektur27Medium);
LV_FONT_DECLARE(ui_font_Tektur13Bold);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
