// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ChargingScreen = NULL;
lv_obj_t * ui_CharingScreenBatteryMetter1 = NULL;
lv_obj_t * ui_CharingScreenImgChargeStatus1 = NULL;
lv_obj_t * ui_CharingScreenImgBatteryStatus1 = NULL;
lv_obj_t * ui_SldBattery1 = NULL;
lv_obj_t * ui_CharingScreenlbBatteryPercent1 = NULL;
lv_obj_t * ui_CharingScreenPnTime1 = NULL;
lv_obj_t * ui_CharingScreenlbTime1 = NULL;
// event funtions

// build funtions

void ui_ChargingScreen_screen_init(void)
{
    ui_ChargingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ChargingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChargingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChargingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharingScreenBatteryMetter1 = lv_arc_create(ui_ChargingScreen);
    lv_obj_set_width(ui_CharingScreenBatteryMetter1, lv_pct(100));
    lv_obj_set_height(ui_CharingScreenBatteryMetter1, lv_pct(100));
    lv_obj_set_x(ui_CharingScreenBatteryMetter1, 0);
    lv_obj_set_y(ui_CharingScreenBatteryMetter1, -1);
    lv_obj_set_align(ui_CharingScreenBatteryMetter1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_CharingScreenBatteryMetter1, 0);
    lv_arc_set_bg_angles(ui_CharingScreenBatteryMetter1, 60, 120);
    lv_arc_set_mode(ui_CharingScreenBatteryMetter1, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_bg_color(ui_CharingScreenBatteryMetter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CharingScreenBatteryMetter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CharingScreenBatteryMetter1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CharingScreenBatteryMetter1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CharingScreenBatteryMetter1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CharingScreenBatteryMetter1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CharingScreenBatteryMetter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CharingScreenBatteryMetter1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CharingScreenBatteryMetter1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_CharingScreenBatteryMetter1, lv_color_hex(0xF5F5F5),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CharingScreenBatteryMetter1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CharingScreenBatteryMetter1, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_CharingScreenBatteryMetter1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CharingScreenBatteryMetter1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CharingScreenBatteryMetter1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CharingScreenImgChargeStatus1 = lv_img_create(ui_ChargingScreen);
    lv_img_set_src(ui_CharingScreenImgChargeStatus1, &ui_img_charge_on_png);
    lv_obj_set_width(ui_CharingScreenImgChargeStatus1, 33);
    lv_obj_set_height(ui_CharingScreenImgChargeStatus1, 33);
    lv_obj_set_x(ui_CharingScreenImgChargeStatus1, 95);
    lv_obj_set_y(ui_CharingScreenImgChargeStatus1, 395);
    lv_obj_add_flag(ui_CharingScreenImgChargeStatus1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CharingScreenImgChargeStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CharingScreenImgChargeStatus1, &ui_img_charge_on_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_CharingScreenImgBatteryStatus1 = lv_img_create(ui_ChargingScreen);
    lv_img_set_src(ui_CharingScreenImgBatteryStatus1, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_CharingScreenImgBatteryStatus1, 38);
    lv_obj_set_height(ui_CharingScreenImgBatteryStatus1, 38);
    lv_obj_set_x(ui_CharingScreenImgBatteryStatus1, 352);
    lv_obj_set_y(ui_CharingScreenImgBatteryStatus1, 395);
    lv_obj_add_flag(ui_CharingScreenImgBatteryStatus1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CharingScreenImgBatteryStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SldBattery1 = lv_slider_create(ui_CharingScreenImgBatteryStatus1);
    lv_slider_set_value(ui_SldBattery1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SldBattery1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SldBattery1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SldBattery1, 32);
    lv_obj_set_height(ui_SldBattery1, 16);
    lv_obj_set_align(ui_SldBattery1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SldBattery1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SldBattery1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldBattery1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SldBattery1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SldBattery1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SldBattery1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SldBattery1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SldBattery1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SldBattery1, lv_color_hex(0x00FF4F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldBattery1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SldBattery1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldBattery1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CharingScreenlbBatteryPercent1 = lv_label_create(ui_ChargingScreen);
    lv_obj_set_width(ui_CharingScreenlbBatteryPercent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharingScreenlbBatteryPercent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharingScreenlbBatteryPercent1, -2);
    lv_obj_set_y(ui_CharingScreenlbBatteryPercent1, 188);
    lv_obj_set_align(ui_CharingScreenlbBatteryPercent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharingScreenlbBatteryPercent1, "0%");
    lv_obj_set_style_text_color(ui_CharingScreenlbBatteryPercent1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharingScreenlbBatteryPercent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharingScreenlbBatteryPercent1, &ui_font_Tektur16Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharingScreenPnTime1 = lv_obj_create(ui_ChargingScreen);
    lv_obj_set_width(ui_CharingScreenPnTime1, 100);
    lv_obj_set_height(ui_CharingScreenPnTime1, 28);
    lv_obj_set_x(ui_CharingScreenPnTime1, 3);
    lv_obj_set_y(ui_CharingScreenPnTime1, -149);
    lv_obj_set_align(ui_CharingScreenPnTime1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CharingScreenPnTime1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CharingScreenPnTime1, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CharingScreenPnTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharingScreenlbTime1 = lv_label_create(ui_CharingScreenPnTime1);
    lv_obj_set_width(ui_CharingScreenlbTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharingScreenlbTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CharingScreenlbTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharingScreenlbTime1, "00:00 AM");
    lv_obj_set_style_text_color(ui_CharingScreenlbTime1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CharingScreenlbTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharingScreenlbTime1, &ui_font_Tektur18Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ChargingScreen_screen_destroy(void)
{
    if(ui_ChargingScreen) lv_obj_del(ui_ChargingScreen);

    // NULL screen variables
    ui_ChargingScreen = NULL;
    ui_CharingScreenBatteryMetter1 = NULL;
    ui_CharingScreenImgChargeStatus1 = NULL;
    ui_CharingScreenImgBatteryStatus1 = NULL;
    ui_SldBattery1 = NULL;
    ui_CharingScreenlbBatteryPercent1 = NULL;
    ui_CharingScreenPnTime1 = NULL;
    ui_CharingScreenlbTime1 = NULL;

}
