// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_SpeedMetterBG = NULL;
lv_obj_t * ui_SpeedMetter = NULL;
lv_obj_t * ui_BatteryMetter = NULL;
lv_obj_t * ui_ImgChargeStatus = NULL;
lv_obj_t * ui_ImgBatteryStatus = NULL;
lv_obj_t * ui_SldBattery = NULL;
lv_obj_t * ui_lbOdoValue = NULL;
lv_obj_t * ui_lbOdo = NULL;
lv_obj_t * ui_lbOdoKm = NULL;
lv_obj_t * ui_lbSpeedValue = NULL;
lv_obj_t * ui_lbSpeedUnit = NULL;
lv_obj_t * ui_imgWarning = NULL;
lv_obj_t * ui_imgXinNhanLeft = NULL;
lv_obj_t * ui_imgCosPha = NULL;
lv_obj_t * ui_imgGear = NULL;
lv_obj_t * ui_imgTemOver = NULL;
lv_obj_t * ui_imgXinNhanRight = NULL;
lv_obj_t * ui_lbBatteryPercent = NULL;
lv_obj_t * ui_lbSpeed20 = NULL;
lv_obj_t * ui_lbSpeed40 = NULL;
lv_obj_t * ui_lbSpeed60 = NULL;
lv_obj_t * ui_lbSpeed80 = NULL;
lv_obj_t * ui_lbSpeed100 = NULL;
lv_obj_t * ui_lbSpeed120 = NULL;
lv_obj_t * ui_lbSpeed140 = NULL;
lv_obj_t * ui_lbSpeed160 = NULL;
lv_obj_t * ui_lbSpeed0 = NULL;
lv_obj_t * ui_pnTime = NULL;
lv_obj_t * ui_lbTime = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_lbTrip = NULL;
lv_obj_t * ui_lbTripKm = NULL;
lv_obj_t * ui_lbTripValue = NULL;
lv_obj_t * ui_pnDot10 = NULL;
lv_obj_t * ui_pnDot30 = NULL;
lv_obj_t * ui_pnDot50 = NULL;
lv_obj_t * ui_pnDot70 = NULL;
lv_obj_t * ui_pnDot90 = NULL;
lv_obj_t * ui_pnDot110 = NULL;
lv_obj_t * ui_pnDot130 = NULL;
lv_obj_t * ui_pnDot1 = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedMetterBG = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_SpeedMetterBG, lv_pct(100));
    lv_obj_set_height(ui_SpeedMetterBG, lv_pct(100));
    lv_obj_set_align(ui_SpeedMetterBG, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_SpeedMetterBG, 0, 160);
    lv_arc_set_value(ui_SpeedMetterBG, 160);
    lv_arc_set_bg_angles(ui_SpeedMetterBG, 135, 45);
    lv_obj_set_style_bg_color(ui_SpeedMetterBG, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedMetterBG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedMetterBG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpeedMetterBG, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedMetterBG, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedMetterBG, 46, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SpeedMetterBG, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedMetterBG, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedMetterBG, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SpeedMetterBG, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedMetter = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_SpeedMetter, lv_pct(100));
    lv_obj_set_height(ui_SpeedMetter, lv_pct(100));
    lv_obj_set_align(ui_SpeedMetter, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_SpeedMetter, 0, 160);
    lv_arc_set_value(ui_SpeedMetter, 0);
    lv_arc_set_bg_angles(ui_SpeedMetter, 135, 45);
    lv_obj_set_style_bg_color(ui_SpeedMetter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedMetter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedMetter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpeedMetter, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedMetter, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedMetter, 46, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SpeedMetter, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedMetter, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedMetter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SpeedMetter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryMetter = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_BatteryMetter, lv_pct(100));
    lv_obj_set_height(ui_BatteryMetter, lv_pct(100));
    lv_obj_set_x(ui_BatteryMetter, 0);
    lv_obj_set_y(ui_BatteryMetter, -1);
    lv_obj_set_align(ui_BatteryMetter, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_BatteryMetter, 0);
    lv_arc_set_bg_angles(ui_BatteryMetter, 60, 120);
    lv_arc_set_mode(ui_BatteryMetter, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_bg_color(ui_BatteryMetter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryMetter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatteryMetter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatteryMetter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatteryMetter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatteryMetter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryMetter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatteryMetter, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryMetter, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_BatteryMetter, lv_color_hex(0xF5F5F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryMetter, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryMetter, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryMetter, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatteryMetter, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryMetter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImgChargeStatus = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_ImgChargeStatus, &ui_img_charge_off_png);
    lv_obj_set_width(ui_ImgChargeStatus, 33);
    lv_obj_set_height(ui_ImgChargeStatus, 33);
    lv_obj_set_x(ui_ImgChargeStatus, 95);
    lv_obj_set_y(ui_ImgChargeStatus, 395);
    lv_obj_add_flag(ui_ImgChargeStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgChargeStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ImgChargeStatus, &ui_img_charge_on_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_ImgBatteryStatus = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_ImgBatteryStatus, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_ImgBatteryStatus, 38);
    lv_obj_set_height(ui_ImgBatteryStatus, 38);
    lv_obj_set_x(ui_ImgBatteryStatus, 352);
    lv_obj_set_y(ui_ImgBatteryStatus, 395);
    lv_obj_add_flag(ui_ImgBatteryStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBatteryStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SldBattery = lv_slider_create(ui_ImgBatteryStatus);
    lv_slider_set_value(ui_SldBattery, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SldBattery) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SldBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SldBattery, 32);
    lv_obj_set_height(ui_SldBattery, 16);
    lv_obj_set_align(ui_SldBattery, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SldBattery, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SldBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SldBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SldBattery, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SldBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SldBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SldBattery, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SldBattery, lv_color_hex(0x00FF4F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SldBattery, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldBattery, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lbOdoValue = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbOdoValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbOdoValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbOdoValue, 4);
    lv_obj_set_y(ui_lbOdoValue, -105);
    lv_obj_set_align(ui_lbOdoValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbOdoValue, "--------");
    lv_obj_set_style_text_color(ui_lbOdoValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbOdoValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbOdoValue, &ui_font_Tektur37Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbOdo = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbOdo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbOdo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbOdo, -57);
    lv_obj_set_y(ui_lbOdo, -81);
    lv_obj_set_align(ui_lbOdo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbOdo, "odo");
    lv_obj_set_style_text_color(ui_lbOdo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbOdo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbOdo, &ui_font_Tektur16Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbOdoKm = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbOdoKm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbOdoKm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbOdoKm, -169);
    lv_obj_set_y(ui_lbOdoKm, -81);
    lv_obj_set_align(ui_lbOdoKm, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbOdoKm, "km");
    lv_obj_set_style_text_color(ui_lbOdoKm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbOdoKm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbOdoKm, &ui_font_Tektur16Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeedValue = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbSpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeedValue, "0");
    lv_obj_set_style_text_color(ui_lbSpeedValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbSpeedValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeedValue, &ui_font_Tektur128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeedUnit = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeedUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeedUnit, 133);
    lv_obj_set_y(ui_lbSpeedUnit, -3);
    lv_obj_set_align(ui_lbSpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeedUnit, "KPH");
    lv_obj_set_style_text_color(ui_lbSpeedUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeedUnit, &ui_font_Tektur17Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWarning = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_imgWarning, &ui_img_warning_off_png);
    lv_obj_set_width(ui_imgWarning, 55);
    lv_obj_set_height(ui_imgWarning, 55);
    lv_obj_set_x(ui_imgWarning, 80);
    lv_obj_set_y(ui_imgWarning, 201);
    lv_obj_add_flag(ui_imgWarning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_imgWarning, &ui_img_warning_on_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_imgXinNhanLeft = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_imgXinNhanLeft, &ui_img_left_off_png);
    lv_obj_set_width(ui_imgXinNhanLeft, 44);
    lv_obj_set_height(ui_imgXinNhanLeft, 42);
    lv_obj_set_x(ui_imgXinNhanLeft, 85);
    lv_obj_set_y(ui_imgXinNhanLeft, 288);
    lv_obj_add_flag(ui_imgXinNhanLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgXinNhanLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_imgXinNhanLeft, &ui_img_left_on_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_imgCosPha = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_imgCosPha, &ui_img_cos_off_png);
    lv_obj_set_width(ui_imgCosPha, 49);
    lv_obj_set_height(ui_imgCosPha, 36);
    lv_obj_set_x(ui_imgCosPha, 149);
    lv_obj_set_y(ui_imgCosPha, 288);
    lv_obj_add_flag(ui_imgCosPha, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgCosPha, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_imgCosPha, 13);
    lv_obj_set_style_bg_img_src(ui_imgCosPha, &ui_img_cos_on_png, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_img_src(ui_imgCosPha, &ui_img_pha_on_png, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_img_src(ui_imgCosPha, &ui_img_pha_on_png, LV_PART_MAIN | LV_STATE_USER_3);

    ui_imgGear = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_imgGear, &ui_img_n_png);
    lv_obj_set_width(ui_imgGear, 28);
    lv_obj_set_height(ui_imgGear, 24);
    lv_obj_set_x(ui_imgGear, 228);
    lv_obj_set_y(ui_imgGear, 294);
    lv_obj_add_flag(ui_imgGear, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgGear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_imgGear, 13);
    lv_obj_set_style_bg_img_src(ui_imgGear, &ui_img_d_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_imgTemOver = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_imgTemOver, &ui_img_over_tem_off_png);
    lv_obj_set_width(ui_imgTemOver, 32);
    lv_obj_set_height(ui_imgTemOver, 29);
    lv_obj_set_x(ui_imgTemOver, 60);
    lv_obj_set_y(ui_imgTemOver, 68);
    lv_obj_set_align(ui_imgTemOver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTemOver, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgTemOver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_imgTemOver, 13);
    lv_obj_set_style_bg_img_src(ui_imgTemOver, &ui_img_over_tem_on_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_imgXinNhanRight = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_imgXinNhanRight, &ui_img_right_off_png);
    lv_obj_set_width(ui_imgXinNhanRight, 44);
    lv_obj_set_height(ui_imgXinNhanRight, 42);
    lv_obj_set_x(ui_imgXinNhanRight, 128);
    lv_obj_set_y(ui_imgXinNhanRight, 68);
    lv_obj_set_align(ui_imgXinNhanRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgXinNhanRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgXinNhanRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_imgXinNhanRight, 13);
    lv_obj_set_style_bg_img_src(ui_imgXinNhanRight, &ui_img_right_on_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_lbBatteryPercent = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbBatteryPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBatteryPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbBatteryPercent, -2);
    lv_obj_set_y(ui_lbBatteryPercent, 188);
    lv_obj_set_align(ui_lbBatteryPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBatteryPercent, "0%");
    lv_obj_set_style_text_color(ui_lbBatteryPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbBatteryPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbBatteryPercent, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbBatteryPercent, &ui_font_Tektur16Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed20 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed20, -212);
    lv_obj_set_y(ui_lbSpeed20, 44);
    lv_obj_set_align(ui_lbSpeed20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed20, "20");
    lv_obj_set_style_text_color(ui_lbSpeed20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed20, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed40 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed40, -201);
    lv_obj_set_y(ui_lbSpeed40, -81);
    lv_obj_set_align(ui_lbSpeed40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed40, "40");
    lv_obj_set_style_text_color(ui_lbSpeed40, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed40, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed60 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed60, -120);
    lv_obj_set_y(ui_lbSpeed60, -179);
    lv_obj_set_align(ui_lbSpeed60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed60, "60");
    lv_obj_set_style_text_color(ui_lbSpeed60, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed60, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed80 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed80, 0);
    lv_obj_set_y(ui_lbSpeed80, -217);
    lv_obj_set_align(ui_lbSpeed80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed80, "80");
    lv_obj_set_style_text_color(ui_lbSpeed80, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed80, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed100 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed100, 114);
    lv_obj_set_y(ui_lbSpeed100, -183);
    lv_obj_set_align(ui_lbSpeed100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed100, "100");
    lv_obj_set_style_text_color(ui_lbSpeed100, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed100, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed120 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed120, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed120, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed120, 198);
    lv_obj_set_y(ui_lbSpeed120, -88);
    lv_obj_set_align(ui_lbSpeed120, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed120, "120");
    lv_obj_set_style_text_color(ui_lbSpeed120, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed120, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed120, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed120, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed140 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed140, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed140, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed140, 214);
    lv_obj_set_y(ui_lbSpeed140, 42);
    lv_obj_set_align(ui_lbSpeed140, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed140, "140");
    lv_obj_set_style_text_color(ui_lbSpeed140, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed140, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed140, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed140, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed160 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed160, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed160, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed160, 179);
    lv_obj_set_y(ui_lbSpeed160, 129);
    lv_obj_set_align(ui_lbSpeed160, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed160, "160");
    lv_obj_set_style_text_color(ui_lbSpeed160, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed160, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed160, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed160, 445, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed0 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbSpeed0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed0, -153);
    lv_obj_set_y(ui_lbSpeed0, 140);
    lv_obj_set_align(ui_lbSpeed0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed0, "0");
    lv_obj_set_style_text_color(ui_lbSpeed0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed0, &ui_font_Tektur24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lbSpeed0, 445, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnTime = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnTime, 100);
    lv_obj_set_height(ui_pnTime, 28);
    lv_obj_set_x(ui_pnTime, 3);
    lv_obj_set_y(ui_pnTime, -149);
    lv_obj_set_align(ui_pnTime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnTime, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbTime = lv_label_create(ui_pnTime);
    lv_obj_set_width(ui_lbTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbTime, "00:00 AM");
    lv_obj_set_style_text_color(ui_lbTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbTime, &ui_font_Tektur18Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_Panel2, 166);
    lv_obj_set_height(ui_Panel2, 56);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 131);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbTrip = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lbTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTrip, -11);
    lv_obj_set_y(ui_lbTrip, 18);
    lv_obj_set_align(ui_lbTrip, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbTrip, "trip 1");
    lv_obj_set_style_text_font(ui_lbTrip, &ui_font_Tektur16Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbTripKm = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lbTripKm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTripKm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTripKm, 13);
    lv_obj_set_y(ui_lbTripKm, 19);
    lv_obj_set_align(ui_lbTripKm, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbTripKm, "km");
    lv_obj_set_style_text_font(ui_lbTripKm, &ui_font_Tektur16Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbTripValue = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lbTripValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTripValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTripValue, 0);
    lv_obj_set_y(ui_lbTripValue, -9);
    lv_obj_set_align(ui_lbTripValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbTripValue, "--------");
    lv_obj_set_style_text_font(ui_lbTripValue, &ui_font_Tektur27Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot10 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot10, 10);
    lv_obj_set_height(ui_pnDot10, 10);
    lv_obj_set_x(ui_pnDot10, -190);
    lv_obj_set_y(ui_pnDot10, 106);
    lv_obj_set_align(ui_pnDot10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot30 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot30, 10);
    lv_obj_set_height(ui_pnDot30, 10);
    lv_obj_set_x(ui_pnDot30, -219);
    lv_obj_set_y(ui_pnDot30, -18);
    lv_obj_set_align(ui_pnDot30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot30, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot50 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot50, 10);
    lv_obj_set_height(ui_pnDot50, 10);
    lv_obj_set_x(ui_pnDot50, -172);
    lv_obj_set_y(ui_pnDot50, -139);
    lv_obj_set_align(ui_pnDot50, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot50, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot50, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot50, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot70 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot70, 10);
    lv_obj_set_height(ui_pnDot70, 10);
    lv_obj_set_x(ui_pnDot70, -63);
    lv_obj_set_y(ui_pnDot70, -206);
    lv_obj_set_align(ui_pnDot70, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot70, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot70, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot70, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot70, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot90 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot90, 10);
    lv_obj_set_height(ui_pnDot90, 10);
    lv_obj_set_x(ui_pnDot90, 60);
    lv_obj_set_y(ui_pnDot90, -209);
    lv_obj_set_align(ui_pnDot90, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot90, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot90, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot90, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot90, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot110 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot110, 10);
    lv_obj_set_height(ui_pnDot110, 10);
    lv_obj_set_x(ui_pnDot110, 166);
    lv_obj_set_y(ui_pnDot110, -139);
    lv_obj_set_align(ui_pnDot110, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot110, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot110, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot110, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot110, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot110, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot110, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot130 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot130, 10);
    lv_obj_set_height(ui_pnDot130, 10);
    lv_obj_set_x(ui_pnDot130, 215);
    lv_obj_set_y(ui_pnDot130, -23);
    lv_obj_set_align(ui_pnDot130, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot130, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot130, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot130, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot130, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot130, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot130, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnDot1 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_pnDot1, 10);
    lv_obj_set_height(ui_pnDot1, 10);
    lv_obj_set_x(ui_pnDot1, 191);
    lv_obj_set_y(ui_pnDot1, 101);
    lv_obj_set_align(ui_pnDot1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnDot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnDot1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnDot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnDot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_SpeedMetterBG = NULL;
    ui_SpeedMetter = NULL;
    ui_BatteryMetter = NULL;
    ui_ImgChargeStatus = NULL;
    ui_ImgBatteryStatus = NULL;
    ui_SldBattery = NULL;
    ui_lbOdoValue = NULL;
    ui_lbOdo = NULL;
    ui_lbOdoKm = NULL;
    ui_lbSpeedValue = NULL;
    ui_lbSpeedUnit = NULL;
    ui_imgWarning = NULL;
    ui_imgXinNhanLeft = NULL;
    ui_imgCosPha = NULL;
    ui_imgGear = NULL;
    ui_imgTemOver = NULL;
    ui_imgXinNhanRight = NULL;
    ui_lbBatteryPercent = NULL;
    ui_lbSpeed20 = NULL;
    ui_lbSpeed40 = NULL;
    ui_lbSpeed60 = NULL;
    ui_lbSpeed80 = NULL;
    ui_lbSpeed100 = NULL;
    ui_lbSpeed120 = NULL;
    ui_lbSpeed140 = NULL;
    ui_lbSpeed160 = NULL;
    ui_lbSpeed0 = NULL;
    ui_pnTime = NULL;
    ui_lbTime = NULL;
    ui_Panel2 = NULL;
    ui_lbTrip = NULL;
    ui_lbTripKm = NULL;
    ui_lbTripValue = NULL;
    ui_pnDot10 = NULL;
    ui_pnDot30 = NULL;
    ui_pnDot50 = NULL;
    ui_pnDot70 = NULL;
    ui_pnDot90 = NULL;
    ui_pnDot110 = NULL;
    ui_pnDot130 = NULL;
    ui_pnDot1 = NULL;

}
