---
name: Build Documentation

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  doxygen:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Build Documentation
        uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          doxyfile-path: Doxyfile
