---
name: Linting & Formatting

on:
  merge_group: {}
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          clean: true
          fetch-tags: true

      - uses: oxsecurity/megalinter@v9
        env:
          APPLY_FIXES: all
          VALIDATE_ALL_CODEBASE: true
          GITHUB_STATUS_REPORTER: true
          MARKDOWN_SUMMARY_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Linter Report
          path: |
            megalinter-reports
      - name: Git Config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
